### ISSUE TITLE
Unit-aware xarray functionality

### ISSUE THREAD

**Issue by clbarnes** [JaneliaSciComp/xarray-ome-ngff#2]
https://xarray.dev/blog/introducing-pint-xarray

There are cases where it may be convenient for coordinate arrays to be unit-aware, which pint-xarray does nicely. However, pint is quite slow to import, so it may not be preferred. What we could do, at least, is replace the `unit` attribute on the `transforms_to_coords` function with `units`, which means that any downstream user simply needs to call `coord_dataarray.pint.quantify()` for those units to be automatically picked up.

**Comment by d-v-b** [comment]
I'm open to that. If pint is a problem, should we look into dropping it as a dependency?

**Comment by clbarnes** [comment]
Hadn't even spotted that pint was in this package! Pint isn't causing me any problems, just aware that there are cases where it can be slow, but anyone using this package is probably going to be doing significant amounts of IO and possibly big maths so it's probably not significant in the grand scheme of things. It means that we can provide unit-aware coordinates by default, which is nice.

**Comment by clbarnes** [comment]
As far as I can tell, xarray actually strips its coordinate arrays of their units so that it can cast them to `pandas.Index`es. I'd have thought coordinate arrays would be the #1 place you'd want to keep units...

Anyway, this boils down to just renaming unit/units, which I see is being discussed (by you) at the OME end, so probably no action needed here.

**Comment by d-v-b** [comment]
closed by changes in #3
